#!/usr/bin/env bash 

bnr() {
    printf -v _b "%80s" ""
    set -- "${1:0:24}"
    printf "\n%s\n==%*s%s%*s==\n%s\n\n" "${_b// /=}" $((38-${#1}/2)) "" "$1" $((38-(${#1}+1)/2)) "" "${_b// /=}"
}

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ========= INSTALLING DEPENDENCIES PACMAN ========================
dependencies=(base-devel gcc git nano sxhkd alacritty xorg-xrandr polybar ttf-inconsolata ttf-jetbrains-mono ttf-jetbrains-mono-nerd ttf-terminus-nerd ttf-font-awesome xclip pavucontrol pipewire pipewire-pulse pipewire-alsa wireplumber playerctl networkmanager zsh zsh-autosuggestions zsh-syntax-highlighting zsh-history-substring-search eza neovim unzip wget curl ripgrep fd python-pip python-black nodejs npm shfmt thunar mousepad dunst libnotify python-gobject rofi xdg-user-dirs maim sddm qt6-svg qt6-virtualkeyboard qt6-multimedia qt6-declarative gst-libav netcat zathura blueman feh qalculate-gtk galculator htop mpv okular ranger tree zip glow bash-language-server rsync xorg-xsetroot xorg-xset firefox)

bnr "INSTALLING DEPENDENCIES WITH PACMAN"
sudo pacman -S --needed --noconfirm "${dependencies[@]}"


# ========= INSTALLING YAY AND DEPENDENCIES ======================
bnr "INSTALLING YAY"
if ! command -v yay &> /dev/null; then
    tmpdir=$(mktemp -d)
    git clone https://aur.archlinux.org/yay.git "$tmpdir/yay"
    cd "$tmpdir/yay"
    makepkg -si --noconfirm
    cd "$DOTFILES_DIR"
    rm -rf "$tmpdir"
fi

bnr "INSTALLING DEPENDENCIES WITH YAY"
dependencies_yay=(spotify spicetify-cli rofi-greenclip neofetch whatsdesk)
yay -S --needed --noconfirm "${dependencies_yay[@]}"

bnr "INSTALLING EWW"
yay -S --needed --noconfirm eww

# ========= PREPARING DIRECTORIES ================================
bnr "INSTALLING DEPENDENCIES WITH YAY"
if [ ! -e "$HOME/.config/user-dirs.dirs" ]; then 
    LC_ALL=C xdg-user-dirs-update --force
fi


# ========= CONFIGURING SERVICES =================================
bnr "SETTING UP SERVICES"
systemctl --user enable --now pipewire pipewire-pulse wireplumber
sudo systemctl disable --now dhcpcd netctl systemd-networkd iwd
systemctl enable NetworkManager

# ========= COPY FOLDERS =========================================
bnr "CREATING AND COPY FOLDERS"
mkdir -p "$HOME/.config"
mkdir -p "$HOME/.local/bin"
mkdir -p "$HOME/.local/share"
mkdir -p "$HOME/.local/share/fonts"

rsync -a "$DOTFILES_DIR/config/." "$HOME/.config"
rsync -a "$DOTFILES_DIR/local/share/." "$HOME/.local/share"
rsync -a "$DOTFILES_DIR/local/bin/." "$HOME/.local/bin"
rsync -a "$DOTFILES_DIR/fonts/home/." "$HOME/.local/share/fonts"
rsync -a "$DOTFILES_DIR/.zshrc" "$HOME"

sudo mkdir -p "/usr/share/fonts"
sudo rsync -a "$DOTFILES_DIR/fonts/root/." "/usr/share/fonts"

fc-cache -rv
sudo fc-cache -rv

# ========= SPOTIFY =========================================
bnr "SETTING UP SPOTIFY"
if [ -d /opt/spotify ]; then
    sudo chmod a+wr /opt/spotify
    sudo chmod -R a+wr /opt/spotify/Apps
fi
mkdir -p "$HOME/.config/spotify"
touch "$HOME/.config/spotify/prefs"
spicetify backup apply
spicetify config current_theme text
spicetify config color_scheme Dark
spicetify config extensions adblock.js
spicetify config custom_apps marketplace

# ===== CHANGING SHELL BASH TO ZSH ==========================
bnr "CHANGE SHELL BASH TO ZSH"
chsh -s "$(command -v zsh)"

# ========= GREETER ========================================
bnr "SETTING UP GREETER"
while true; do
    read -rp "do you want to install greeter sddm with the berserk theme? [y/n]: " yn
    case $yn in
        [Yy]* )
            sudo systemctl disable display-manager
            sudo systemctl enable sddm
            sudo mkdir -p /usr/share/sddm
            sudo mkdir -p /usr/share/sddm/themes
            sudo rsync -a "$DOTFILES_DIR/share-root/sddm/theme/berserk-theme" /usr/share/sddm/themes
            sudo cp "$DOTFILES_DIR/share-root/sddm.conf" /etc/sddm.conf
            break
            ;;
        [Nn]* ) break ;;
        * ) printf " error: just write 'y' or 'n'\n\n" ;;
    esac
done



# ===== CHANGING DEFAULT BROWSER TO ZEN ======================
bnr "CHANGING DEFAULT BROWSER"
if ls ~/.local/share/applications | grep -i "zen"; then 
    while true; do
        read -rp "do you want to change default browser to Zen? [y/n]: " yn
        case $yn in
            [Yy]* )  
                unset BROWSER
                xdg-settings set default-web-browser ZenBrowser.desktop
                break
                ;;
            [Nn]* ) exit ;;
            * ) printf " error: just write 'y' or 'n'\n\n" ;;
        esac
    done
fi

bnr "FINISH"
printf "please, reboot your OS\n"

