#modules.ini

########################################################

[module/sep2]
type = custom/text
label = "  "

########################################################

[module/bspwm]
type = internal/bspwm

enable-click = true
enable-scroll = true
reverse-scroll = true
pin-workspaces = true
occupied-scroll = false

ws-icon-0 = 1;󰑊
ws-icon-1 = 2;󰑊
ws-icon-2 = 3;󰑊
ws-icon-3 = 4;󰑊
ws-icon-4 = 5;󰑊
ws-icon-5 = 6;󰑊


format = <label-state>

label-focused = 󰀚
label-focused-foreground = ${color.fg}

label-occupied = %icon%
label-occupied-foreground= ${color.fg}

label-urgent = %icon%

label-empty = %icon%
label-empty-foreground = ${color.blackg}

label-separator = "  "
label-separator-padding = 0
label-separator-foreground = ${color.fg}

########################################################

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = true
interval = 5
format-volume = <label-volume>
format-volume-prefix-padding-right = 2pt
label-volume = "%percentage%"
label-volume-foreground = ${color.fg}
format-mute = <label-muted>
format-mute-prefix-padding-right = 1pt
label-muted = "-1"
# click-right = OppenApps --soundcontrol
click-right = pavucontrol

########################################################

[module/network]
type = internal/network
interface = ${system.sys_network_interface}
interval = 3.0
accumulate-stats = true
unknown-as-up = true
format-connected = %{A1:OpenApps --netmanager:}C%{A}
; format-connected = "C"
format-connected-prefix-padding-right = 3pt
speed-unit = ""

format-disconnected = %{A1:OpenApps --netmanager:}D%{A}
; format-disconnected = "C"
format-disconnected-prefix = ""
format-disconnected-prefix-padding-right = 3pt 

########################################################

[module/date]
type = internal/date
interval = 1.0
time = %H:%M
format = <label>
label = "%{A1:OpenApps --calendar:}%time%%{A}"

########################################################

[module/battery]
type = internal/battery
full-at = 99
battery = ${system.sys_battery}
adapter = ${system.sys_adapter}
poll-interval = 2
time-format = %H:%M

format-charging = "%percentage%% "
format-discharging = "%percentage%% "
format-full = "%percentage%% "

########################################################
