#!/usr/bin/env bash

export PATH="$HOME/.config/bspwm/src:$PATH"

# ====== WORKSPACES ================================================

for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
    bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6'
done

bspc config split_ratio				0.52
bspc config single_monocle			true
bspc config borderless_monocle		false 
bspc config gapless_monocle			false

bspc config focus_follows_pointer true
bspc config pointer_motion_interval 8 # valor 5 si tienen monitor 200HZ 

bspc config pointer_modifier		mod4
bspc config pointer_action1 		move
bspc config pointer_action2 		resize_side
bspc config pointer_action3 		resize_corner

# ====== AUTOSTART =================================================

"$HOME/.config/bspwm/src/SetSysVars"
"$HOME/.config/bspwm/rice/Theme.sh"
pkill -f SpotifyNotification.sh
"$HOME/.local/bin/SpotifyNotification.sh" &

# ==================================================================

xsetroot -cursor_name left_ptr &
pidof -q sxhkd || { sxhkd & }
setxkbmap latam &
xset r rate 250 33 &
vmware-user-suid-wrapper & #eliminar esto, es para copiar y pegar contenido de la vmware a la pc fisica
pidof -q dunst || { dunst & }
pidof -q greenclip || { greenclip daemon & }

